# source 'http://rubygems.org'
source 'http://ruby.taobao.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'

group :development do
  gem 'rake'
  gem 'racksh'
  gem 'shotgun'
  gem 'yard'
  gem 'haml'
  gem 'sass'
  gem 'builder', '~> 3.0.0'
  gem 'slim'
  gem 'temple'
  gem 'coffee-script'
  gem 'rdoc'
  gem 'kramdown'
  gem 'creole'
  gem 'markaby'
  gem 'radius'
  gem 'rabl'
  gem 'liquid'
  gem 'stylus'
  gem 'nokogiri'
  gem 'less'
  gem 'rdiscount'
  gem 'execjs'
  gem 'therubyracer'
  gem 'i18n', :git => 'http://github.com/svenfuchs/i18n.git'
  gem 'better_errors'
  gem 'mongo'
  gem 'bson_ext'
  gem 'mongoid', '~> 3.1.4'
  # seems mongoid does not support activemodel 4.0
  # gem 'activerecord', '~> 4.0.0'
  gem 'activerecord', '~> 3.2.0'
  gem 'sinatra-partial'
  gem 'sinatra-activerecord'
  gem 'sinatra-flash'
  gem 'sinatra-redirect-with-flash'
  gem 'rack-parser', :require => 'rack/parser'
  gem 'tux'
  gem 'pg'
  gem 'sqlite3'
#  gem 'binding_of_caller'
  # uncomment this for more advanced features: #TODO: what's the diff
  # gem 'binding_of_caller'`
end

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-spork'
  gem 'rubocop'
  gem 'guard-rubocop'
  gem 'simplecov'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'cucumber'
#  gem 'machinist'
#  gem 'guard-minitest'
#  gem 'guard-test'
end
